import FaceRegistration from './FaceRegistration';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';

const ProfileEditForm = ({
  user,
  nickname,
  onNicknameChange,
  onNicknameSubmit,
  selectedCategories,
  availableCategories,
  onCategoryToggle,
  onCategoriesSubmit,
  validationErrors,
  successMessage,
  isSubmitting,
  isLoading,
  isDeactivating,
  isAutoGeneratedNickname,
  onSaveAll,
  onCancel,
  onDeactivateAccount,
  // 프로필 이미지 관련 props
  profileImagePreview,
  profileImageMessage,
  isUploadingProfileImage,
  onProfileImageSelect,
  profileImageInputRef,
  onProfileImageUpload,
  onProfileImageDelete,
  // 얼굴 등록 관련 props
  isCameraActive,
  isVideoReady,
  cameraError,
  isRegisteringFace,
  facePreview,
  faceMessage,
  videoRef,
  fileInputRef,
  onCameraToggle,
  onFaceImageSelect,
  onCapturePhoto,
  onStopCamera,
  onRegisterFace,
  onResetFace
}) => {

  return (
    <div className="space-y-6">
      {/* 기본 정보 카드 */}
      <Card className="bg-white shadow-sm border border-gray-200">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg font-semibold">기본 정보</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">이메일</Label>
            <Input
              type="email"
              id="email"
              value={user?.email || ''}
              disabled
              className="bg-white cursor-not-allowed"
            />
            <p className="text-xs text-gray-500">이메일은 변경할 수 없습니다.</p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="provider">로그인 제공자</Label>
            <Input
              type="text"
              id="provider"
              value={user?.provider === 'local' ? '일반 로그인' :
                user?.provider === 'kakao' ? '카카오' :
                  user?.provider === 'naver' ? '네이버' :
                    user?.provider === 'google' ? '구글' : user?.provider || ''}
              disabled
              className="bg-white cursor-not-allowed"
            />
          </div>
        </CardContent>
      </Card>

      {/* 프로필 이미지 카드 */}
      <Card className="bg-white shadow-sm border border-gray-200">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg font-semibold">프로필 이미지</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center gap-4">
            <div className="w-20 h-20 rounded-full overflow-hidden border-2 border-gray-300 flex items-center justify-center bg-gray-200 flex-shrink-0">
              {profileImagePreview ? (
                <img
                  src={profileImagePreview}
                  alt="프로필 미리보기"
                  className="w-full h-full object-cover"
                />
              ) : (
                <span className="text-3xl text-gray-400">👤</span>
              )}
            </div>

            <div className="flex-1 space-y-2">
              <Input
                type="file"
                accept="image/*"
                ref={profileImageInputRef}
                onChange={onProfileImageSelect}
                disabled={isUploadingProfileImage || isLoading}
                className="bg-white"
              />
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={onProfileImageUpload}
                  disabled={isUploadingProfileImage || isLoading}
                  className="flex-1 bg-white border-gray-300 hover:bg-blue-50 hover:border-blue-400 hover:text-blue-700 active:bg-blue-100 active:border-blue-500 transition-all duration-200"
                >
                  {isUploadingProfileImage ? '업로드 중...' : '이미지 업로드'}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={onProfileImageDelete}
                  disabled={isUploadingProfileImage || isLoading}
                  className="flex-1 bg-white border-gray-300 hover:bg-red-50 hover:border-red-400 hover:text-red-700 active:bg-red-100 active:border-red-500 transition-all duration-200"
                >
                  이미지 삭제
                </Button>
              </div>
              <p className="text-xs text-gray-500">
                JPG, PNG 등 이미지 파일만 가능하며, 최대 10MB까지 허용됩니다.
              </p>
              {profileImageMessage && (
                <div className={`p-2 rounded text-sm ${profileImageMessage.includes('실패')
                  ? 'bg-red-50 text-red-700 border border-red-200'
                  : 'bg-green-50 text-green-700 border border-green-200'
                  }`}>
                  {profileImageMessage}
                </div>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* 닉네임 수정 카드 */}
      <Card className="bg-white shadow-sm border border-gray-200">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg font-semibold">닉네임 수정</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="nickname">닉네임</Label>
            <Input
              type="text"
              id="nickname"
              value={nickname}
              onChange={onNicknameChange}
              className={`bg-white ${validationErrors.nickname ? 'border-red-500' : ''}`}
              placeholder="닉네임을 입력하세요 (2-20자, 한글/영문/숫자)"
              disabled={isSubmitting || isLoading}
              maxLength={20}
            />
            {validationErrors.nickname && (
              <p className="text-sm text-red-500">{validationErrors.nickname}</p>
            )}
            <p className="text-xs text-gray-500">한글, 영문, 숫자만 사용 가능합니다. (2-20자)</p>
          </div>
        </CardContent>
      </Card>

      {/* 관심 카테고리 수정 카드 */}
      <Card className="bg-white shadow-sm border border-gray-200">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg font-semibold">관심 카테고리 수정</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="categories">
              관심 카테고리 <span className="text-gray-500 text-sm">(최대 3개 선택 가능)</span>
            </Label>
            <div className="flex flex-wrap gap-2">
              {availableCategories.map((category) => {
                const isSelected = selectedCategories.includes(category);
                const isDisabled = !isSelected && selectedCategories.length >= 3;
                return (
                  <button
                    key={category}
                    type="button"
                    onClick={() => onCategoryToggle(category)}
                    disabled={isSubmitting || isLoading || isDisabled}
                    className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${isSelected
                      ? 'bg-blue-600 text-white'
                      : isDisabled
                        ? 'bg-gray-200 text-gray-400 cursor-not-allowed'
                        : 'bg-white text-gray-700 hover:bg-gray-100 border border-gray-300'
                      }`}
                  >
                    {category}
                    {isSelected && <span className="ml-1">✓</span>}
                  </button>
                );
              })}
            </div>
            {validationErrors.categories && (
              <p className="text-sm text-red-500">{validationErrors.categories}</p>
            )}
            {selectedCategories.length > 0 && (
              <p className="text-sm text-gray-600">
                선택된 카테고리: {selectedCategories.join(', ')} ({selectedCategories.length}/3)
              </p>
            )}
          </div>
        </CardContent>
      </Card>

      {/* 얼굴 등록 카드 */}
      <Card className="bg-white shadow-sm border border-gray-200">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg font-semibold">얼굴 등록</CardTitle>
        </CardHeader>
        <CardContent>
          <FaceRegistration
            isCameraActive={isCameraActive}
            isVideoReady={isVideoReady}
            cameraError={cameraError}
            isRegisteringFace={isRegisteringFace}
            isLoading={isLoading}
            facePreview={facePreview}
            faceMessage={faceMessage}
            videoRef={videoRef}
            fileInputRef={fileInputRef}
            onCameraToggle={onCameraToggle}
            onFaceImageSelect={onFaceImageSelect}
            onCapturePhoto={onCapturePhoto}
            onStopCamera={onStopCamera}
            onRegisterFace={onRegisterFace}
            onResetFace={onResetFace}
          />
        </CardContent>
      </Card>

      {successMessage && (
        <div className="p-4 bg-green-50 border border-green-200 rounded-lg text-green-700 text-center shadow-sm">
          {successMessage}
        </div>
      )}

      {/* 하단 수정/취소 버튼 */}
      <div className="flex flex-col sm:flex-row gap-4 pt-6">
        <Button
          onClick={onSaveAll}
          disabled={isSubmitting || isLoading}
          className="flex-1 bg-blue-600 hover:bg-blue-700 text-white shadow-sm h-11"
          size="lg"
        >
          {isSubmitting ? '수정 중...' : '수정'}
        </Button>
        <Button
          onClick={onCancel}
          variant="outline"
          disabled={isSubmitting || isLoading}
          className="flex-1 bg-white border-gray-300 hover:bg-gray-50 h-11"
          size="lg"
        >
          취소
        </Button>
      </div>

      {/* 회원탈퇴 섹션 */}
      <Card className="bg-white shadow-sm border border-red-200 mt-8">
        <CardHeader className="pb-4">
          <CardTitle className="text-lg font-semibold text-red-600">회원탈퇴</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <p className="text-sm text-gray-600">
              계정을 비활성화하면 서비스 이용이 불가능해지며, 일부 데이터는 법적 보관 의무에 따라 일정 기간 보관될 수 있습니다.
            </p>
            <p className="text-xs text-gray-500">
              회원탈퇴 후에는 계정 복구가 어려울 수 있으니 신중히 결정해주세요.
            </p>
          </div>
          <Button
            onClick={onDeactivateAccount}
            variant="outline"
            disabled={isSubmitting || isLoading || isDeactivating}
            className="w-full sm:w-auto border-red-300 text-red-600 hover:bg-red-50 hover:border-red-400"
          >
            {isDeactivating ? '탈퇴 처리 중...' : '회원탈퇴'}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
};

export default ProfileEditForm;
