import FaceRegistration from './FaceRegistration';

const ProfileEditForm = ({
  user,
  nickname,
  onNicknameChange,
  selectedCategories,
  availableCategories,
  onCategoryToggle,
  validationErrors,
  successMessage,
  isSubmitting,
  isLoading,
  isAutoGeneratedNickname,
  onNicknameSubmit,
  onCategoriesSubmit,
  onCancel,
  // 얼굴 등록 관련 props
  isCameraActive,
  isVideoReady,
  cameraError,
  isRegisteringFace,
  facePreview,
  faceMessage,
  videoRef,
  fileInputRef,
  onCameraToggle,
  onFaceImageSelect,
  onCapturePhoto,
  onStopCamera,
  onRegisterFace,
  onResetFace
}) => {
  return (
    <div className="profile-edit-container">
      <div className="profile-edit-box">
        <div className="profile-header">
          <h2 className="profile-edit-title">프로필 수정</h2>
          <p className="profile-subtitle">계정 정보와 얼굴 인식 설정을 관리할 수 있습니다</p>
        </div>
        
        {isAutoGeneratedNickname && (
          <div className="info-message">
            <div className="info-message-title">
              💡 닉네임 안내
            </div>
            <div className="info-message-content">
              현재 닉네임이 자동으로 생성되었습니다. 원하는 닉네임으로 변경해주세요.
            </div>
          </div>
        )}

        <div className="profile-edit-form">
          {/* 기본 정보 섹션 */}
          <div className="form-section">
            <h3 className="section-title">기본 정보</h3>
            
            <div className="form-group">
              <label htmlFor="email">이메일</label>
              <input
                type="email"
                id="email"
                value={user?.email || ''}
                disabled
                className="disabled-input"
                style={{ backgroundColor: '#f5f5f5', cursor: 'not-allowed' }}
              />
              <small style={{ color: '#666', fontSize: '12px', marginTop: '4px', display: 'block' }}>
                이메일은 변경할 수 없습니다.
              </small>
            </div>

            <div className="form-group">
              <label htmlFor="provider">로그인 제공자</label>
              <input
                type="text"
                id="provider"
                value={user?.provider === 'local' ? '일반 로그인' : 
                       user?.provider === 'kakao' ? '카카오' :
                       user?.provider === 'naver' ? '네이버' :
                       user?.provider === 'google' ? '구글' : user?.provider || ''}
                disabled
                className="disabled-input"
                style={{ backgroundColor: '#f5f5f5', cursor: 'not-allowed' }}
              />
            </div>
          </div>

          {/* 닉네임 수정 섹션 */}
          <div className="form-section">
            <h3 className="section-title">닉네임 수정</h3>
            <form onSubmit={onNicknameSubmit}>
              <div className="form-group">
                <label htmlFor="nickname">닉네임</label>
                <input
                  type="text"
                  id="nickname"
                  value={nickname}
                  onChange={onNicknameChange}
                  className={validationErrors.nickname ? 'error' : ''}
                  placeholder="닉네임을 입력하세요 (2-20자, 한글/영문/숫자)"
                  disabled={isSubmitting || isLoading}
                  maxLength={20}
                />
                {validationErrors.nickname && (
                  <span className="error-message">{validationErrors.nickname}</span>
                )}
                <small style={{ color: '#666', fontSize: '12px', marginTop: '4px', display: 'block' }}>
                  한글, 영문, 숫자만 사용 가능합니다. (2-20자)
                </small>
              </div>
              <div className="button-group-inline">
                <button 
                  type="submit" 
                  className="submit-button" 
                  disabled={isSubmitting || isLoading}
                >
                  {isSubmitting ? '수정 중...' : '닉네임 저장'}
                </button>
              </div>
            </form>
          </div>

          {/* 관심 카테고리 수정 섹션 */}
          <div className="form-section">
            <h3 className="section-title">관심 카테고리 수정</h3>
            <form onSubmit={onCategoriesSubmit}>
              <div className="form-group">
                <label htmlFor="categories">
                  관심 카테고리 <span className="category-hint">(최대 3개 선택 가능)</span>
                </label>
                <div className="category-selector">
                  {availableCategories.map((category) => {
                    const isSelected = selectedCategories.includes(category);
                    const isDisabled = !isSelected && selectedCategories.length >= 3;
                    return (
                      <button
                        key={category}
                        type="button"
                        className={`category-chip ${isSelected ? 'selected' : ''} ${isDisabled ? 'disabled' : ''}`}
                        onClick={() => onCategoryToggle(category)}
                        disabled={isSubmitting || isLoading || isDisabled}
                      >
                        {category}
                        {isSelected && <span className="check-icon">✓</span>}
                      </button>
                    );
                  })}
                </div>
                {validationErrors.categories && (
                  <span className="error-message">{validationErrors.categories}</span>
                )}
                {selectedCategories.length > 0 && (
                  <div className="category-selected-info">
                    선택된 카테고리: {selectedCategories.join(', ')} ({selectedCategories.length}/3)
                  </div>
                )}
              </div>
              <div className="button-group-inline">
                <button 
                  type="submit" 
                  className="submit-button" 
                  disabled={isSubmitting || isLoading}
                >
                  {isSubmitting ? '수정 중...' : '카테고리 저장'}
                </button>
              </div>
            </form>
          </div>

          <FaceRegistration
            isCameraActive={isCameraActive}
            isVideoReady={isVideoReady}
            cameraError={cameraError}
            isRegisteringFace={isRegisteringFace}
            isLoading={isLoading}
            facePreview={facePreview}
            faceMessage={faceMessage}
            videoRef={videoRef}
            fileInputRef={fileInputRef}
            onCameraToggle={onCameraToggle}
            onFaceImageSelect={onFaceImageSelect}
            onCapturePhoto={onCapturePhoto}
            onStopCamera={onStopCamera}
            onRegisterFace={onRegisterFace}
            onResetFace={onResetFace}
          />

          {successMessage && (
            <div className="success-message" style={{ 
              textAlign: 'center', 
              padding: '10px', 
              backgroundColor: '#d4edda', 
              borderRadius: '6px', 
              border: '1px solid #c3e6cb',
              color: '#155724',
              marginBottom: '20px',
              marginTop: '20px'
            }}>
              {successMessage}
            </div>
          )}

          <div className="button-group">
            <button 
              type="button" 
              onClick={onCancel}
              className="cancel-button"
              disabled={isSubmitting || isLoading}
            >
              취소
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProfileEditForm;
