import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { fetchUserInfoAsync } from '../slices/authSlice';
import { updateProfile } from '../api/authApi';
import './ProfileEdit.css';

const ProfileEdit = () => {
  const [nickname, setNickname] = useState('');
  const [validationErrors, setValidationErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [successMessage, setSuccessMessage] = useState('');

  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { user, isLoading } = useSelector((state) => state.auth);

  // 사용자 정보 로드
  useEffect(() => {
    if (user) {
      setNickname(user.nickname || '');
    } else {
      // 사용자 정보가 없으면 조회 시도
      dispatch(fetchUserInfoAsync());
    }
  }, [user, dispatch]);

  // 사용자 정보가 로드된 후 닉네임 설정
  useEffect(() => {
    if (user?.nickname) {
      setNickname(user.nickname);
    }
  }, [user]);

  // OAuth 로그인으로 자동 생성된 닉네임인지 확인 (예: 한해찬_1, 한해찬_2)
  const isAutoGeneratedNickname = user?.nickname && /_\d+$/.test(user.nickname);

  // 유효성 검사
  const validate = () => {
    const errors = {};

    if (!nickname.trim()) {
      errors.nickname = '닉네임을 입력해주세요.';
    } else if (nickname.trim().length < 2) {
      errors.nickname = '닉네임은 2자 이상이어야 합니다.';
    } else if (nickname.trim().length > 20) {
      errors.nickname = '닉네임은 20자 이하여야 합니다.';
    } else if (!/^[가-힣a-zA-Z0-9]+$/.test(nickname.trim())) {
      errors.nickname = '닉네임은 한글, 영문, 숫자만 사용할 수 있습니다.';
    }

    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  // 프로필 수정 핸들러
  const handleSubmit = async (e) => {
    e.preventDefault();
    setValidationErrors({});
    setSuccessMessage('');

    if (!validate()) {
      return;
    }

    // 현재 닉네임과 동일한 경우
    if (nickname.trim() === user?.nickname) {
      setSuccessMessage('변경 사항이 없습니다.');
      return;
    }

    setIsSubmitting(true);

    try {
      const updatedUser = await updateProfile(nickname.trim());
      
      // Redux 상태 업데이트
      dispatch(fetchUserInfoAsync());
      
      setSuccessMessage('프로필이 성공적으로 수정되었습니다!');
      
      // 2초 후 홈으로 이동
      setTimeout(() => {
        navigate('/');
      }, 2000);
    } catch (error) {
      const errorMessage = error.response?.data?.message || error.message || '프로필 수정에 실패했습니다.';
      setValidationErrors({ nickname: errorMessage });
    } finally {
      setIsSubmitting(false);
    }
  };

  // 취소 핸들러
  const handleCancel = () => {
    navigate('/');
  };

  return (
    <div className="profile-edit-container">
      <div className="profile-edit-box">
        <h2 className="profile-edit-title">프로필 수정</h2>
        
        {isAutoGeneratedNickname && (
          <div className="info-message" style={{ 
            marginBottom: '20px',
            padding: '12px',
            backgroundColor: '#fff3cd',
            borderRadius: '6px',
            border: '1px solid #ffc107',
            color: '#856404'
          }}>
            <div style={{ fontWeight: '600', marginBottom: '4px' }}>
              💡 닉네임 안내
            </div>
            <div style={{ fontSize: '14px' }}>
              현재 닉네임이 자동으로 생성되었습니다. 원하는 닉네임으로 변경해주세요.
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="profile-edit-form">
          <div className="form-group">
            <label htmlFor="email">이메일</label>
            <input
              type="email"
              id="email"
              value={user?.email || ''}
              disabled
              className="disabled-input"
              style={{ backgroundColor: '#f5f5f5', cursor: 'not-allowed' }}
            />
            <small style={{ color: '#666', fontSize: '12px', marginTop: '4px', display: 'block' }}>
              이메일은 변경할 수 없습니다.
            </small>
          </div>

          <div className="form-group">
            <label htmlFor="nickname">닉네임</label>
            <input
              type="text"
              id="nickname"
              value={nickname}
              onChange={(e) => {
                setNickname(e.target.value);
                setValidationErrors({ ...validationErrors, nickname: '' });
                setSuccessMessage('');
              }}
              className={validationErrors.nickname ? 'error' : ''}
              placeholder="닉네임을 입력하세요 (2-20자, 한글/영문/숫자)"
              disabled={isSubmitting || isLoading}
              maxLength={20}
            />
            {validationErrors.nickname && (
              <span className="error-message">{validationErrors.nickname}</span>
            )}
            <small style={{ color: '#666', fontSize: '12px', marginTop: '4px', display: 'block' }}>
              한글, 영문, 숫자만 사용 가능합니다. (2-20자)
            </small>
          </div>

          <div className="form-group">
            <label htmlFor="provider">로그인 제공자</label>
            <input
              type="text"
              id="provider"
              value={user?.provider === 'local' ? '일반 로그인' : 
                     user?.provider === 'kakao' ? '카카오' :
                     user?.provider === 'naver' ? '네이버' :
                     user?.provider === 'google' ? '구글' : user?.provider || ''}
              disabled
              className="disabled-input"
              style={{ backgroundColor: '#f5f5f5', cursor: 'not-allowed' }}
            />
          </div>

          {successMessage && (
            <div className="success-message" style={{ 
              textAlign: 'center', 
              padding: '10px', 
              backgroundColor: '#d4edda', 
              borderRadius: '6px', 
              border: '1px solid #c3e6cb',
              color: '#155724',
              marginBottom: '10px'
            }}>
              {successMessage}
            </div>
          )}

          <div className="button-group">
            <button 
              type="button" 
              onClick={handleCancel}
              className="cancel-button"
              disabled={isSubmitting || isLoading}
            >
              취소
            </button>
            <button 
              type="submit" 
              className="submit-button" 
              disabled={isSubmitting || isLoading}
            >
              {isSubmitting ? '수정 중...' : '수정하기'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ProfileEdit;
